### ISSUE TITLE
Not working on 1.19.2

### ISSUE THREAD

**Issue by rlnt** [CorgiTaco/ShutupExperimentalSettings#16]
MC version: 1.19.2
mod version: 1.0.5
forge version: 43.1.3

[latest log](https://pastebin.com/2vm5xePw)
![](https://i.imgur.com/aPnlGCM.png)

**Comment by VallenFrostweaver** [comment]
Can confirm
![image](https://user-images.githubusercontent.com/13642054/187441877-c07d0e3f-c172-4bbe-8fcb-4355ad334758.png)

**Comment by Reshirou** [comment]
Same here

**Comment by Maxwelljones** [comment]
Same here.

**Comment by LolJohn11** [comment]
Same here

**Comment by erazare** [comment]
same here.. 43.1.43 & 43.1.47 ineffectual

**Comment by szunakabeats** [comment]
same

**Comment by szunakabeats** [comment]
for those who want the msg to be gone now use this [mod here](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus) !

**Comment by Alan-Yan-CanMeng** [comment]
same

**Comment by kreezxil** [comment]
same so sad.

**Comment by FooterManDev** [comment]
It's been too long, we need an update! 

> for those who want the msg to be gone now use this [mod here](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus) !

Not around for 1.19.2 :(

**Comment by KeVrX** [comment]
same

**Comment by MindBrain27** [comment]
> It's been too long, we need an update!
> 
> > for those who want the msg to be gone now use this [mod here](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus) !
> 
> Not around for 1.19.2 :(

Yes it is.

**Comment by SneaX060** [comment]
Same don't working in 1.19.2 but Yeetus mod work

**Comment by K4N0** [comment]
Confirmed not working shutupexperimentalsettings-1.0.5.jar

**Comment by GingleMeow** [comment]
Same.

**Comment by szunakabeats** [comment]
Just leave it. The mod is dead. Use the mod that i posted above and everything is fine

**Comment by rlnt** [comment]
I agree that the mod seems dead. Since there are already alternatives out there that are updated frequently, I will close this one.

Link to the alternative mod: https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus
