### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by benbenlaw** [CorgiTaco/ShutupExperimentalSettings#2]
Added and it doesnt work
forge 36.0.9 
minecraft 1.16.5 S
your mod version 1.0.2

**Comment by Sunekaer** [comment]
Same issue on forge 36.0.7

**Comment by CorgiTaco** [comment]
It works for me?

**Comment by Sunekaer** [comment]
What info do you need Corgi?

**Comment by CorgiTaco** [comment]
Alright yall were right

**Comment by benbenlaw** [comment]
if you need any logs ect i can help just let me know

**Comment by aaronhowser1** [comment]
I am also having this problem

**Comment by MelanX** [comment]
Same problem here

**Comment by CorgiTaco** [comment]
Apologies for taking a while, fixed it here: https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings/files/3188120

**Comment by kreezxil** [comment]
no longer works in 36.1.4

**Comment by kreezxil** [comment]
doesn't even appear in search of the latest.log 
![image](https://user-images.githubusercontent.com/3880072/114319604-c2190d80-9ad7-11eb-8dc1-773cff152959.png)

client latest log: https://gist.github.com/3cfdfb90e309ad641eb89447cff3f072
