### ISSUE TITLE
players cant use commands/command blocks dont work either

### ISSUE THREAD

**Issue by mangogamr** [CorgiTaco/ShutupExperimentalSettings#3]
trying to set up a server that is using this to make the sky blocks (sky bees on curseforge)
as an op i can make an island. but when i deop i cant. so then i try to set up a command block and it does nothing. even when directly using my name instead of @p
i can use command blocks with the /give command though. but not /island or /skyblock commands
 i am using the server files for the 3.0.3b version of sky bees. i have not changed anything in the configs.

**Comment by ZandercraftGames** [comment]
@mangogamr This issue likely isn't caused by this mod as it does not modify anything related to command blocks. If you remove all other mods, does this issue still occur? If not, it is due to one of your other mods.

**Comment by CorgiTaco** [comment]
This mod doesnt go near command blocks.
